
 
-- select script to fetch data

select up.USER_PROFILE_ID,up.FULLNAME,up.DESIGNATION,up.NID,up.PERMANENT_ADDRESS,up.PRESENT_ADDRESS,up.EMAIL,up.GENDER,up.MOBILE,up.CREATION_DATE,up.STATUS,
ui.LOGINID,ui.USERPASSWORD,ui.ISACTIVE,ui.USERCREATIONDATE,ui.PRIVILEGETYPE,ui.CODE,ui.PASSWORD_CHANGE_DATE,ui.USER_ID,ui.USER_CAT_ID,
ui.IS_OTP_ENABLE,ui.IS_PROFILE_LOCK,ui.PROFILE_LOCK_UNTILL,ui.IS_MULTILOGIN_ENABLE,ui.PASSWORD_WRONG_ATTEMPTS,ui.STAKEHOLDER_CAT_ID
from TBLUSERINFO ui
inner join USER_PROFILE up on ui.LOGINID=up.USER_PROFILE_ID
where  ui.ISACTIVE='Y' and ui.STATUS='OPEN'
and up.STATUS='APPROVED';

-- insert script generation

SELECT 'INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, NID,  DESIGNATION, PERMANENT_ADDRESS, PRESENT_ADDRESS, REMARKS) 
VALUES (' || autoincreament || ', ' || 1 || ', ' || 'DSE_EIN' || ', ' || ui.LOGINID|| ', ' || up.FULLNAME || ', ' || up.MOBILE || ', ' || up.EMAIL|| ', ' || up.GENDER ||', ' || up.NID ||', ' || up.DESIGNATION || ', ' || up.PERMANENT_ADDRESS|| ', ' || up.PRESENT_ADDRESS|| ');'
from TBLUSERINFO ui
inner join USER_PROFILE up on ui.LOGINID=up.USER_PROFILE_ID
where  ui.ISACTIVE='Y' and ui.STATUS='OPEN'
and up.STATUS='APPROVED';
ORDER BY ui.LOGINID;

----------------------------------------------------------------------
----------------------------------------------------------------------

-- MIS and Development
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (1, 1, 'DSE_EIN', '496','Md Saiful Islam', '01916158165', 'saiful.islam496@dse.com.bd', 'Male','Senior Executive');

INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (2, 1, 'DSE_EIN', '108','Golam Kibria', '01730318173', 'golam.kibria@dse.com.bd', 'Male','Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (3, 1, 'DSE_EIN', '52','kamruzzaman', '01730032372', 'm.kamruzzaman@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (4, 1, 'DSE_EIN', '94','Abdul Kader', '01730334787', 'abdul.kader@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (5, 1, 'DSE_EIN', '490','Kamrul Hasan', '01723472276', 'kamrul.hasan490@dse.com.bd', 'Male','Senior Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (6, 1, 'DSE_EIN', '493','Mahsin Kabir', '01722868449', 'mahsin.kabir@dse.com.bd', 'Male','Senior Executive');

-- TREC Affairs
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (7, 1, 'DSE_EIN', '55','Mohammad Haroon-Or-Rashid Pathan', '01730032377', 'haroon.pathan@dse.com.bd', 'Male','Assistant General Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (8, 1, 'DSE_EIN', '58','Md. Delower Hossain', '01713425822', 'delower.hossain@dse.com.bd', 'Male','Senior Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (9, 1, 'DSE_EIN', '111','Md. Abdur Rahim Bhuiyan', '01713425824', 'rahim.bhuiyan@dse.com.bd', 'Male','Senior Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (10, 1, 'DSE_EIN', '114','Abdul Mannan Bashar', '01713425853', 'mannan.bashar@dse.com.bd', 'Male','Deputy Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (11, 1, 'DSE_EIN', '133','Mohammad Shazzad Hossain', '01730701798', 'shazzad.hossain@dse.com.bd', 'Male','Senior Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (12, 1, 'DSE_EIN', '137','Mohammad Matiur Rahman', '01709656746,', 'matiur.rahman@dse.com.bd', 'Male','Junior Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (13, 1, 'DSE_EIN', '138','Md. Manirul Islam', '01709631407,', 'manirul.islam@dse.com.bd', 'Male','Junior Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (14, 1, 'DSE_EIN', '169','Rabeya Khatun', '0191,', 'rabeya.khatun@dse.com.bd', 'Female','	Sr. Office Assistant');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (15, 1, 'DSE_EIN', '181','Md. Sahab Uddin', '01713494629,', 'sahab.uddin@dse.com.bd', 'Male','Jr. Office Assistant');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (16, 1, 'DSE_EIN', '360','Tasneem Tabassum', '01917001700', 'tasneem.tabassum@dse.com.bd', 'Female','Sr. Office Assistant');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (17, 1, 'DSE_EIN', '366','Mariwam Akter', '01730738119', 'mariwam.akter@dse.com.bd', 'Female','Executive');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (18, 1, 'DSE_EIN', '524','Nasrin Sultana', '0191', 'nasrin.sultana@dse.com.bd', 'Female','Senior Executive');

-- Application Support
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (19, 1, 'DSE_EIN', '30','Mohammad Ruhul Amin', '0171342583', 'ruhul.amin@dse.com.bd', 'Male','Deputy General Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (20, 1, 'DSE_EIN', '44','Md. Mahmudul Hasan', '01713425840', 'mahmudul.hasan@dse.com.bd', 'Male','Deputy General Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (21, 1, 'DSE_EIN', '46','Gazi Makhdum Hossain', '01713425841', 'makhdum.hossain@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (22, 1, 'DSE_EIN', '74','Faysal Ibne Khair', '01730334783', 'faysal.ibnekhair@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (23, 1, 'DSE_EIN', '90','Md. Meherab Ali', '01730334784', 'meherab.ali@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (24, 1, 'DSE_EIN', '91','Ahsan Habib Un Nabi', '01730334781', 'habib.nabi@dse.com.bd', 'Male','Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (25, 1, 'DSE_EIN', '100','Md. Arifur Rahman', '01730318177', 'arif.rahman@dse.com.bd', 'Male','Manager');

-- Network Development
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (26, 1, 'DSE_EIN', '18','Md. Eleas Hosain', '01713425819', 'eleas.hosain@dse.com.bd', 'Male','Deputy General Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (27, 1, 'DSE_EIN', '51','Md. Syful Islam Sumon', '01730032371', 'syful.islam@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (28, 1, 'DSE_EIN', '63','Dewan Muhammad Sariful Islam', '01730022798', 'sariful.islam@dse.com.bd', 'Male','Senior Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (29, 1, 'DSE_EIN', '82','S.M. Bhayejid', '01730334782', 'sm.bhayejid@dse.com.bd', 'Male','Manager');
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (30, 1, 'DSE_EIN', '555','Talha Zubaer', '01730334782', 'talha.zubaer@dse.com.bd', 'Male','Executive');

-- System and Market Administration
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (31, 1, 'DSE_EIN', '57','Sadat Maruf Hasnayen', '01730032379', 'sadat.hasnayen@dse.com.bd', 'Male','Senior Manager');

-- Product & Market Development	
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (32, 1, 'DSE_EIN', '53','Kamrun Nahar', '01730032373', 'kamrun.nahar@dse.com.bd', 'Female','Assistant General Manager');

INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (33, 1, 'DSE_EIN', '146','Hossne Ara Ferdoushi', '0171', 'hossneara.ferdoushi@dse.com.bd', 'Female','Senior Executive');

-- 	Monitoring & Compliance Department (MCD)
INSERT INTO USER_PROFILE (USER_PROFILE_ID, USER_CAT_ID, USER_IDENTIFIER_NAME, USER_IDENTIFIER_VALUE, FULL_NAME, MOBILE, EMAIL, GENDER, DESIGNATION)
VALUES (34, 1, 'DSE_EIN', '419','S. M. Arman', '0171', 'sm.arman@dse.com.bd', 'Male','Manager');

commit;
select * from USER_PROFILE;


