
----------- Find tables in an Oracle database where data exists--------------------------------

 SELECT table_name, TO_NUMBER(
        EXTRACTVALUE(
            xmltype(
                DBMS_XMLGEN.GETXML('SELECT COUNT(*) c FROM ' || table_name)
            ),
            '/ROWSET/ROW/C'
        )
    ) AS num_rows
    FROM user_tables;

--------------------------------------------------------------------------------

SELECT constraint_name, table_name
FROM user_constraints
WHERE r_constraint_name IN (
  SELECT constraint_name
  FROM user_constraints
  WHERE table_name = 'TREC'
    AND constraint_type IN ('P', 'U')
);


delete from PERSONNEL;
delete from DUAL_TREC;
delete from TREC_AUDITOR;
delete from TREC_STATUS;
delete from TREC_CODE;
delete from TREC_NAME;
delete from TREC_AUTHORISED_CAPITAL;
delete from TREC_PAIDUP_CAPITAL;
delete from TREC_PARENT_COMPANY;
delete from TREC_DOCUMENT;
delete from  TREC_NETWORK;
delete from WORKSTATION;
delete from TR_SHARE_HOLDER_MASTER;
delete from TREC;

commit;

-- drop table PERSONNEL;
-- drop table DUAL_TREC;
-- drop table TREC_AUDITOR;
-- drop table TREC_STATUS;
-- drop table TREC_CODE;
-- drop table TREC_NAME;
-- drop table TREC_AUTHORISED_CAPITAL;
-- drop table TREC_PAIDUP_CAPITAL;
-- drop table TREC_PARENT_COMPANY;
-- drop table TREC_DOCUMENT;

-- drop table WORKSTATION;
-- drop table TR_SHARE_HOLDER_MASTER;

--------------------------------------------------------------------------------
TREC_TREC.TREC
--------------------------------------------------------------------------------

CREATE TABLE TREC_TREC.TREC
(
    TREC_ID NUMBER(5,0),
    TREC_NO NUMBER(5,0),
    CODE VARCHAR2(50 CHAR),
    NAME VARCHAR2(255 CHAR),
    E_TIN VARCHAR2(50 CHAR),
    TRADE_LICENSE_NO VARCHAR2(50 CHAR),
    DP_NUMBER VARCHAR2(50 CHAR),
    CATEGORY VARCHAR2(50 CHAR),
    TYPE_OF_COMPANY VARCHAR2(50 CHAR),

    IS_SUBSIDIARY_COMPANY VARCHAR2(50 CHAR),
    --TOTAL_SHARE_QTY NUMBER(16,0),
    TOTAL_SHARE NUMBER(16,2),
    COST_OF_ACQUISITION NUMBER(16,2),
    SECURITY_DEPOSIT NUMBER(16,2),
    --FACE_VALUE FLOAT, -- not used
    --QUALIFICATION_SHARE NUMBER(10,0), -- not used
    MONTH_OF_FINANCIAL_YEAR VARCHAR2(50 CHAR),
    
    NO_OF_MALE_EMP NUMBER(5,0) DEFAULT 0,
    NO_OF_FEMALE_EMP NUMBER(5,0) DEFAULT 0,

    QUORUM_BOARD NUMBER(5,0) DEFAULT 0,
    QUORUM_AGM NUMBER(5,0) DEFAULT 0,

    TREC_ISSUED_DATE DATE,
    DSE_APPROVE_DATE DATE,
    TREC_TRADE_COMMENCE_DATE DATE,
    DLR_TRADE_COMMENCE_DATE DATE,

    RJSC_REG_NO VARCHAR2(50 CHAR),
    RJSC_REG_DATE DATE,
    --RJSC_CERTIFICATE_PATH VARCHAR2(255 CHAR),

    REGISTERED_ADDRESS VARCHAR2(500 CHAR), 
    PHONE_NO VARCHAR2(50 CHAR), 
    PRIMARY_EMAIL VARCHAR2(50 CHAR),
    SECONDARY_EMAIL VARCHAR2(50 CHAR),
    TERTIARY_EMAIL VARCHAR2(50 CHAR),
    WEBSITE VARCHAR2(255 CHAR),
   
    FULLREMARK NCLOB,
    REMARKS VARCHAR2(500 CHAR),
    STATUS VARCHAR2(50 CHAR) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_TREC_TREC_ID PRIMARY KEY (TREC_ID)
);

--alter table TREC add (FACE_VALUE FLOAT);
alter table TREC add (FACE_VALUE NUMBER(6,2));
--ALTER TABLE TREC MODIFY (FACE_VALUE NUMBER(6,2));


-----------------------------------------------------------------
 TREC_STATUS
-----------------------------------------------------------------

CREATE TABLE TREC_STATUS(
    TREC_STATUS_ID NUMBER(10,0) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
  
    EFFECTIVE_DATE DATE,                    -- TREC.BROKER_REGDATE
    END_DATE DATE,
	
    REMARKS VARCHAR2(255),		
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
   
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_TREC_STATUS_ID PRIMARY KEY (TREC_STATUS_ID),
    CONSTRAINT FK_TREC_STATUS_TREC_ID FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID)
);

-----------------------------------------------------------------
 TREC_CODE
-----------------------------------------------------------------

CREATE TABLE TREC_CODE(
    TREC_CODE_ID NUMBER(10,0) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
    CODE VARCHAR2(50) NOT NULL,
    EFFECTIVE_DATE DATE,                    -- TREC.BROKER_REGDATE
    END_DATE DATE,
	REMARKS VARCHAR2(255),		

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_TREC_CODE_ID PRIMARY KEY (TREC_CODE_ID),
    CONSTRAINT FK_TREC_CODE_TREC_ID FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID)
);

-----------------------------------------------------------------
 TREC_NAME
-----------------------------------------------------------------

CREATE TABLE TREC_NAME(
    TREC_NAME_ID NUMBER(10,0) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL, 
    EFFECTIVE_DATE DATE,                    -- TREC.BROKER_REGDATE
    END_DATE DATE,
	REMARKS VARCHAR2(255),		

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_TREC_NAME_ID PRIMARY KEY (TREC_NAME_ID),
    CONSTRAINT FK_TREC_NAME_TREC_ID FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID)
);

-----------------------------------------------------------------
 TREC_DOCUMENT_TYPE
-----------------------------------------------------------------

--drop table TREC_DOCUMENT_TYPE;
CREATE TABLE TREC_DOCUMENT_TYPE(
  TREC_DOCUMENT_TYPE_ID NUMBER(5,0) NOT NULL,
  DOCUMENT_NAME VARCHAR2(255) NOT NULL,
  DOCUMENT_DETAILS VARCHAR2(255 CHAR),
  IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
  constraint PK_TREC_DOCUMENT_TYPE primary key (TREC_DOCUMENT_TYPE_ID)
);


INSERT INTO TREC_DOCUMENT_TYPE (TREC_DOCUMENT_TYPE_ID, DOCUMENT_NAME) 
VALUES (1.0, 'MoA and AoA');
INSERT INTO TREC_DOCUMENT_TYPE (TREC_DOCUMENT_TYPE_ID, DOCUMENT_NAME) 
VALUES (2.0, 'Incorporation Certificate');
INSERT INTO TREC_DOCUMENT_TYPE (TREC_DOCUMENT_TYPE_ID, DOCUMENT_NAME) 
VALUES (3.0, 'Schedule X');
INSERT INTO TREC_DOCUMENT_TYPE (TREC_DOCUMENT_TYPE_ID, DOCUMENT_NAME) 
VALUES (4.0, 'Form XII');

select * from TREC_DOCUMENT_TYPE;

-----------------------------------------------------------------
 TREC_DOCUMENT
-----------------------------------------------------------------

--drop table TREC_DOCUMENT;

CREATE TABLE TREC_DOCUMENT(
    TREC_DOCUMENT_ID NUMBER(10,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL,
    TREC_DOCUMENT_TYPE_ID NUMBER(5,0) NOT NULL,
    ISSUED_DATE DATE,
    DOCUMENT_PATH VARCHAR2(255 CHAR),
    REMARKS VARCHAR2(255 CHAR),

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TREC_DOCUMENT_ID PRIMARY KEY (TREC_DOCUMENT_ID),
    CONSTRAINT FK_TREC_DOCUMENT_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID),
    CONSTRAINT FK_TREC_DOCUMENT_TYPE FOREIGN KEY (TREC_DOCUMENT_TYPE_ID) REFERENCES TREC_DOCUMENT_TYPE(TREC_DOCUMENT_TYPE_ID)
);

-----------------------------------------------------------------
 DUAL_TREC
-----------------------------------------------------------------

CREATE TABLE DUAL_TREC (
    DUAL_TREC_ID NUMBER(5,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL,
    CSE_TREC_NO NUMBER(5,0),
    CSE_TREC_NAME VARCHAR2(255 CHAR),
    CSE_TREC_CODE VARCHAR2(50 CHAR),

    TREC_TRADE_COMMENCE_DATE DATE,
    DLR_TRADE_COMMENCE_DATE DATE,

    REMARKS VARCHAR2(255 CHAR),
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_DUAL_TREC_ID PRIMARY KEY (DUAL_TREC_ID),
    CONSTRAINT FK_DUAL_TREC_TREC_ID_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID) 
);

-----------------------------------------------------------------
 TREC_AUTHORISED_CAPITAL
-----------------------------------------------------------------

CREATE TABLE TREC_AUTHORISED_CAPITAL (
    AUTHORISED_CAP_ID NUMBER(5,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL,
    AUTHORISED_CAPITAL NUMBER(16,2) DEFAULT 0,
    APPROVAL_DATE DATE,
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL ,
    REMARKS VARCHAR2(255 CHAR),
    ADDED_BY VARCHAR2(50) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_AUTHORISED_CAP_ID PRIMARY KEY (AUTHORISED_CAP_ID),
    CONSTRAINT FK_AUTHORISED_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID) 
);

-----------------------------------------------------------------
 TREC_PAIDUP_CAPITAL
-----------------------------------------------------------------

CREATE TABLE TREC_PAIDUP_CAPITAL (
    PAIDUP_CAP_ID NUMBER(5,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL ,
    PAID_UP_CAPITAL NUMBER(16,2) DEFAULT 0,
    APPROVAL_DATE DATE,
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL ,
    REMARKS VARCHAR2(255 CHAR),

    ADDED_BY VARCHAR2(50) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_PAIDUP_CAP_ID PRIMARY KEY (PAIDUP_CAP_ID),
    CONSTRAINT FK_PAIDUP_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID) 
);

-----------------------------------------------------------------
 TREC_AUDITOR
-----------------------------------------------------------------

CREATE TABLE TREC_AUDITOR (
    AUDITOR_ID NUMBER(5,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL,
    NAME VARCHAR2(255 CHAR),
    ADDRESS VARCHAR2(500),
    PHONE VARCHAR2(100),
    FROM_DATE DATE,
    TO_DATE DATE,
    REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL,
    
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_BY VARCHAR2(50),
    UPDATED_AT DATE,
    CONSTRAINT PK_TREC_AUDITOR PRIMARY KEY (AUDITOR_ID),
    CONSTRAINT FK_TREC_AUDITOR_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID)
);

-----------------------------------------------------------------
 TREC_PARENT_COMPANY
-----------------------------------------------------------------

CREATE TABLE TREC_PARENT_COMPANY (
    PARENT_COM_ID NUMBER(5,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL,
    PARENT_COM_NAME VARCHAR2(500) NOT NULL,
    ADDRESS VARCHAR2(500),
    PHONE VARCHAR2(50),
    NO_OF_SHARE_HELD NUMBER(16,2) DEFAULT 0,
    SHARE_PERCENTAGE NUMBER(5,0) DEFAULT 0,
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL ,
    REMARKS VARCHAR2(255 CHAR),
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_COM_ID PRIMARY KEY (PARENT_COM_ID),
    CONSTRAINT FK_COMPANU_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID) 
) ;

-----------------------------------------------------------------
 TREC_NETWORK
-----------------------------------------------------------------

CREATE TABLE TREC_NETWORK (
    TREC_NETWORK_ID NUMBER(5,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL,
    HUB_NO NUMBER(5,0),
    PORT NUMBER(5,0),
    FLOOR VARCHAR2(50),
    IP_ADDRESSES VARCHAR2(255),
    CARD_IP VARCHAR2(50),
    OLD_IP VARCHAR2(50),
    SILO VARCHAR2(5),
    DLUPNO NUMBER(10),
    TMP_DLUPNO VARCHAR2(5),
    HOST_PORT VARCHAR2(10),
    WAN_CON VARCHAR2(5),
    REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE NUMBER(1,0) DEFAULT (1) NOT NULL ,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TREC_NETWORK_ID PRIMARY KEY (TREC_NETWORK_ID),
    CONSTRAINT FK_TREC_NETWORK_TREC FOREIGN KEY (TREC_ID) REFERENCES TREC(TREC_ID) 
) ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_TREC" 
(
 "TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME",
 "E_TIN", "TRADE_LICENSE_NO", "DP_NUMBER", "CATEGORY", "TYPE_OF_COMPANY", "IS_SUBSIDIARY_COMPANY", 
 "TOTAL_SHARE", "COST_OF_ACQUISITION", "SECURITY_DEPOSIT", "MONTH_OF_FINANCIAL_YEAR", "NO_OF_MALE_EMP", "NO_OF_FEMALE_EMP", "QUORUM_BOARD", "QUORUM_AGM",
 "TREC_ISSUED_DATE", "TREC_TRADE_COMMENCE_DATE", "DLR_TRADE_COMMENCE_DATE", "DSE_APPROVE_DATE",
 "RJSC_REG_NO", "RJSC_REG_DATE",
 "REGISTERED_ADDRESS", "PHONE_NO", "PRIMARY_EMAIL", "SECONDARY_EMAIL", "TERTIARY_EMAIL",  "WEBSITE", "FULLREMARK",
 "TREC_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    t.E_TIN,
    t.TRADE_LICENSE_NO,
    t.DP_NUMBER,
    t.CATEGORY,
    t.TYPE_OF_COMPANY,
    t.IS_SUBSIDIARY_COMPANY,
    t.TOTAL_SHARE,
    t.COST_OF_ACQUISITION,
    t.SECURITY_DEPOSIT,
    t.MONTH_OF_FINANCIAL_YEAR,
    t.NO_OF_MALE_EMP,
    t.NO_OF_FEMALE_EMP,
    t.QUORUM_BOARD,
    t.QUORUM_AGM,
    t.TREC_ISSUED_DATE,
    t.TREC_TRADE_COMMENCE_DATE,
    t.DLR_TRADE_COMMENCE_DATE,
    t.DSE_APPROVE_DATE,
    t.RJSC_REG_NO,
    t.RJSC_REG_DATE,
    t.REGISTERED_ADDRESS,
    t.PHONE_NO,
    t.PRIMARY_EMAIL,
    t.SECONDARY_EMAIL,
    t.TERTIARY_EMAIL,
    t.WEBSITE,
    t.FULLREMARK,

    st.TREC_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    st.REMARKS,
    --st.IS_ACTIVE,
    CASE WHEN st.STATUS IN ('ACTIVE', 'SUSPENDED') THEN 1 ELSE 0 END AS IS_ACTIVE,
    st.ADDED_AT,
    st.ADDED_BY

FROM  TREC t
INNER JOIN TREC_STATUS st ON t.TREC_ID = st.TREC_ID  and st.IS_ACTIVE=1
ORDER BY t.TREC_ID;

select * from VW_TREC;

--------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_TREC_STATUS" 
(
 "TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME",
 "E_TIN", "TRADE_LICENSE_NO", "DP_NUMBER", "CATEGORY", "TYPE_OF_COMPANY", "IS_SUBSIDIARY_COMPANY", 
 "TOTAL_SHARE", "COST_OF_ACQUISITION", "SECURITY_DEPOSIT", "MONTH_OF_FINANCIAL_YEAR", "NO_OF_MALE_EMP", "NO_OF_FEMALE_EMP", "QUORUM_BOARD", "QUORUM_AGM",
 "TREC_ISSUED_DATE", "TREC_TRADE_COMMENCE_DATE", "DLR_TRADE_COMMENCE_DATE", "DSE_APPROVE_DATE",
 "RJSC_REG_NO", "RJSC_REG_DATE",
 "REGISTERED_ADDRESS", "PHONE_NO", "PRIMARY_EMAIL", "SECONDARY_EMAIL", "TERTIARY_EMAIL",  "WEBSITE", "FULLREMARK",
 "TREC_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    t.E_TIN,
    t.TRADE_LICENSE_NO,
    t.DP_NUMBER,
    t.CATEGORY,
    t.TYPE_OF_COMPANY,
    t.IS_SUBSIDIARY_COMPANY,
    t.TOTAL_SHARE,
    t.COST_OF_ACQUISITION,
    t.SECURITY_DEPOSIT,
    t.MONTH_OF_FINANCIAL_YEAR,
    t.NO_OF_MALE_EMP,
    t.NO_OF_FEMALE_EMP,
    t.QUORUM_BOARD,
    t.QUORUM_AGM,
    t.TREC_ISSUED_DATE,
    t.TREC_TRADE_COMMENCE_DATE,
    t.DLR_TRADE_COMMENCE_DATE,
    t.DSE_APPROVE_DATE,
    t.RJSC_REG_NO,
    t.RJSC_REG_DATE,
    t.REGISTERED_ADDRESS,
    t.PHONE_NO,
    t.PRIMARY_EMAIL,
    t.SECONDARY_EMAIL,
    t.TERTIARY_EMAIL,
    t.WEBSITE,
    t.FULLREMARK,

    st.TREC_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    st.REMARKS,
    st.IS_ACTIVE,
    st.ADDED_AT,
    st.ADDED_BY

FROM  TREC t
INNER JOIN TREC_STATUS st ON t.TREC_ID = st.TREC_ID 
ORDER BY t.TREC_ID;

select * from VW_TREC_STATUS;

--------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_TREC_CODE" 
(
 "TREC_ID", "TREC_NO", "TREC_NAME",
 "E_TIN", "TRADE_LICENSE_NO", "DP_NUMBER", "CATEGORY", "TYPE_OF_COMPANY", "IS_SUBSIDIARY_COMPANY", 
 "TOTAL_SHARE", "COST_OF_ACQUISITION", "SECURITY_DEPOSIT", "MONTH_OF_FINANCIAL_YEAR", "NO_OF_MALE_EMP", "NO_OF_FEMALE_EMP", "QUORUM_BOARD", "QUORUM_AGM",
 "TREC_ISSUED_DATE", "TREC_TRADE_COMMENCE_DATE", "DLR_TRADE_COMMENCE_DATE", "DSE_APPROVE_DATE",
 "RJSC_REG_NO", "RJSC_REG_DATE",
 "REGISTERED_ADDRESS", "PHONE_NO", "PRIMARY_EMAIL", "SECONDARY_EMAIL", "TERTIARY_EMAIL",  "WEBSITE", "FULLREMARK", 
 "TREC_CODE_ID", "TREC_CODE", "CODE_EFFECTIVE_DATE", "CODE_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.NAME as TREC_NAME,

    t.E_TIN,
    t.TRADE_LICENSE_NO,
    t.DP_NUMBER,
    t.CATEGORY,
    t.TYPE_OF_COMPANY,
    t.IS_SUBSIDIARY_COMPANY,
    t.TOTAL_SHARE,
    t.COST_OF_ACQUISITION,
    t.SECURITY_DEPOSIT,
    t.MONTH_OF_FINANCIAL_YEAR,
    t.NO_OF_MALE_EMP,
    t.NO_OF_FEMALE_EMP,
    t.QUORUM_BOARD,
    t.QUORUM_AGM,
    t.TREC_ISSUED_DATE,
    t.TREC_TRADE_COMMENCE_DATE,
    t.DLR_TRADE_COMMENCE_DATE,
    t.DSE_APPROVE_DATE,
    t.RJSC_REG_NO,
    t.RJSC_REG_DATE,
    t.REGISTERED_ADDRESS,
    t.PHONE_NO,
    t.PRIMARY_EMAIL,
    t.SECONDARY_EMAIL,
    t.TERTIARY_EMAIL,
    t.WEBSITE,
    t.FULLREMARK,

    tc.TREC_CODE_ID,
    tc.CODE as TREC_CODE,
    tc.EFFECTIVE_DATE as CODE_EFFECTIVE_DATE,
    tc.END_DATE as CODE_END_DATE,
    tc.REMARKS,
    tc.IS_ACTIVE,
    tc.ADDED_AT,
    tc.ADDED_BY

FROM  TREC t
INNER JOIN TREC_CODE tc ON t.TREC_ID = tc.TREC_ID 
ORDER BY t.TREC_ID;

select * from VW_TREC_CODE;

--------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_TREC_NAME" 
(
 "TREC_ID", "TREC_NO", "TREC_CODE",
 "E_TIN", "TRADE_LICENSE_NO", "DP_NUMBER", "CATEGORY", "TYPE_OF_COMPANY", "IS_SUBSIDIARY_COMPANY", 
 "TOTAL_SHARE", "COST_OF_ACQUISITION", "SECURITY_DEPOSIT", "MONTH_OF_FINANCIAL_YEAR", "NO_OF_MALE_EMP", "NO_OF_FEMALE_EMP", "QUORUM_BOARD", "QUORUM_AGM",
 "TREC_ISSUED_DATE", "TREC_TRADE_COMMENCE_DATE", "DLR_TRADE_COMMENCE_DATE", "DSE_APPROVE_DATE",
 "RJSC_REG_NO", "RJSC_REG_DATE",
 "REGISTERED_ADDRESS", "PHONE_NO", "PRIMARY_EMAIL", "SECONDARY_EMAIL", "TERTIARY_EMAIL",  "WEBSITE", "FULLREMARK", 
 "TREC_NAME_ID", "TREC_NAME", "NAME_EFFECTIVE_DATE", "NAME_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,

    t.E_TIN,
    t.TRADE_LICENSE_NO,
    t.DP_NUMBER,
    t.CATEGORY,
    t.TYPE_OF_COMPANY,
    t.IS_SUBSIDIARY_COMPANY,
    t.TOTAL_SHARE,
    t.COST_OF_ACQUISITION,
    t.SECURITY_DEPOSIT,
    t.MONTH_OF_FINANCIAL_YEAR,
    t.NO_OF_MALE_EMP,
    t.NO_OF_FEMALE_EMP,
    t.QUORUM_BOARD,
    t.QUORUM_AGM,
    t.TREC_ISSUED_DATE,
    t.TREC_TRADE_COMMENCE_DATE,
    t.DLR_TRADE_COMMENCE_DATE,
    t.DSE_APPROVE_DATE,
    t.RJSC_REG_NO,
    t.RJSC_REG_DATE,
    t.REGISTERED_ADDRESS,
    t.PHONE_NO,
    t.PRIMARY_EMAIL,
    t.SECONDARY_EMAIL,
    t.TERTIARY_EMAIL,
    t.WEBSITE,
    t.FULLREMARK,

    tn.TREC_NAME_ID,
    tn.NAME as TREC_NAME,
    tn.EFFECTIVE_DATE as NAME_EFFECTIVE_DATE,
    tn.END_DATE as NAME_END_DATE,
    tn.REMARKS,
    tn.IS_ACTIVE,
    tn.ADDED_AT,
    tn.ADDED_BY

FROM  TREC t
INNER JOIN TREC_NAME tn ON t.TREC_ID = tn.TREC_ID 
ORDER BY t.TREC_ID;

select * from VW_TREC_NAME;
select * from VW_TREC_DOCUMENT;
--------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_TREC_DOCUMENT" 
(
 "TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME",
 "TREC_DOCUMENT_TYPE_ID", "DOCUMENT_NAME", "DOCUMENT_DETAILS",
 "TREC_DOCUMENT_ID", "ISSUED_DATE", "DOCUMENT_PATH", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    tt.TREC_DOCUMENT_TYPE_ID,
    tt.DOCUMENT_NAME,
    tt.DOCUMENT_DETAILS,

    td.TREC_DOCUMENT_ID,
    td.ISSUED_DATE,
    td.DOCUMENT_PATH,
    td.REMARKS,
    td.IS_ACTIVE,
    td.ADDED_AT,
    td.ADDED_BY

FROM  TREC t
INNER JOIN TREC_DOCUMENT td ON t.TREC_ID = td.TREC_ID 
INNER JOIN TREC_DOCUMENT_TYPE tt ON tt.TREC_DOCUMENT_TYPE_ID = td.TREC_DOCUMENT_TYPE_ID 
ORDER BY t.TREC_ID;

select * from VW_TREC_DOCUMENT;

--------------------------------------------------------------------------------