------------------------------------------------------

SELECT constraint_name, table_name
FROM user_constraints
WHERE r_constraint_name IN (
  SELECT constraint_name
  FROM user_constraints
  WHERE table_name = 'PERSONNEL'
    AND constraint_type IN ('P', 'U')
);

delete from WORKSTATION_AUTH_REP;
delete from TREC_CAMALCO;
delete from TREC_POWER_OF_ATT;
delete from TREC_COMPLIANCE_AUTH;
delete from TREC_HLDR_REPRESENT;
delete from OFFICE_INCHARGE;
delete from OFFICE_COMPL_OFFICER;
delete from AUTH_REP;
delete from PERSONNEL;
commit;


-- Drop the foreign key constraints for each table and key
ALTER TABLE PERSONNEL_OFFICE DROP CONSTRAINT FK_PERSONNEL_OFFICE_PERSON;

-- ADD the foreign key constraints for each table and key
ALTER TABLE PERSONNEL_OFFICE ADD CONSTRAINT FK_PERSONNEL_OFFICE_PERSONNEL
FOREIGN KEY (PERSONNEL_ID) REFERENCES PERSONNEL (PERSONNEL_ID);


------------------------------------------------------
 PERSONNEL
------------------------------------------------------

CREATE TABLE PERSONNEL
(
    PERSONNEL_ID NUMBER(10,0) NOT NULL,
    TREC_ID NUMBER(5,0) NOT NULL , 			-- TREC_BACKUP.MEM_NO 
    BACKUP_ID VARCHAR2(50 CHAR),
    NAME VARCHAR2(255 CHAR) NOT NULL ,    	-- TREC_BACKUP.COMOFF // TREC_BACKUP.OWNER
    SEX VARCHAR2(50 CHAR),
    DATE_OF_BIRTH DATE,
    NAME_OF_FATHER VARCHAR2(255 CHAR),
    NAME_OF_MOTHER VARCHAR2(255 CHAR),
    NAME_OF_SPOUSE VARCHAR2(255 CHAR),
    MAX_EDU_QUALIFICATION VARCHAR2(255 CHAR),
    PRESENT_ADDRESS VARCHAR2(255 CHAR),
    PERMANENT_ADDRESS VARCHAR2(255 CHAR),
    NID VARCHAR2(50 CHAR),
    ETIN VARCHAR2(50 CHAR),
    DESIGNATION VARCHAR2(255 CHAR),              	-- TREC_BACKUP.COMOFFDESIGNATION //  TREC_BACKUP.OWNER_CATE
    DATE_OF_JOINING DATE,
    DATE_OF_EMPLOYMENT_END DATE,
    OFFICIAL_CONTACT_NO VARCHAR2(255 CHAR),      	-- TREC_BACKUP.PHONE_OFF         // TREC_BACKUP.PHONE_PABX
    PERSONAL_CONTACT_NO VARCHAR2(50 CHAR),      	-- TREC_BACKUP.MOBILE            // TREC_BACKUP.PHONE_RES
    OFFICIAL_EMAIL VARCHAR2(255 CHAR),           	-- TREC_BACKUP.E_MAIL
    PERSONAL_EMAIL VARCHAR2(50 CHAR),
    ALTERNATIVE_EMAIL VARCHAR2(50 CHAR),
    FAX VARCHAR2(50 CHAR),					     	-- TREC_BACKUP.FAX
    RESIDENCE_STATUS VARCHAR2(50 CHAR),
    IMAGE_PATH VARCHAR2(255 CHAR),
    SIGNATURE_PATH VARCHAR2(255 CHAR),

    REMARKS VARCHAR2(255 CHAR),
    STATUS VARCHAR2(50 CHAR) NOT NULL,
    STATUS_EFFECTIVE_DATE DATE,
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

    TEMP_DATA VARCHAR2(500 CHAR),

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_PERSONNEL PRIMARY KEY (PERSONNEL_ID),
    CONSTRAINT FK_PERSONNEL_TREC_ID FOREIGN KEY (TREC_ID) REFERENCES TREC (TREC_ID) 
);

--ALTER TABLE PERSONNEL ADD IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL;
--drop table PERSONNEL_STATUS;

------------------------------------------------------
 TREC_HLDR_REPRESENT
------------------------------------------------------

CREATE TABLE TREC_HLDR_REPRESENT(
    TREC_HLDR_REPRESENT_ID NUMBER(10) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
	PERSONNEL_ID NUMBER(10,0) NOT NULL,
	EFFECTIVE_DATE DATE ,
	END_DATE  DATE ,

	REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    constraint PK_TREC_HLDR_REP primary key (TREC_HLDR_REPRESENT_ID),
	constraint FK_TREC_HLDR_REP_TREC foreign key (TREC_ID) references TREC(TREC_ID),
	constraint FK_TREC_HLDR_REP_PERSON foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID)
);

------------------------------------------------------
 TREC_COMPLIANCE_AUTH
------------------------------------------------------

CREATE TABLE TREC_COMPLIANCE_AUTH(
    TREC_COMP_AUTH_ID NUMBER(10) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
	PERSONNEL_ID NUMBER(10,0) NOT NULL,
	EFFECTIVE_DATE DATE ,
	END_DATE  DATE ,

	REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
	
    constraint PK_FK_TREC_COM_AUTH primary key (TREC_COMP_AUTH_ID),
	constraint FK_TREC_COM_AUTH_TREC foreign key (TREC_ID) references TREC(TREC_ID),
	constraint FK_TREC_COM_AUTH_PERSON foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID)
);

------------------------------------------------------
 TREC_POWER_OF_ATT
------------------------------------------------------

CREATE TABLE TREC_POWER_OF_ATT(
    TREC_POW_OF_ATT_ID NUMBER(10) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
	PERSONNEL_ID NUMBER(10,0) NOT NULL,
	EFFECTIVE_DATE DATE ,
	END_DATE  DATE ,
	
	REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    constraint PK_FK_TREC_POW_OF_ATT primary key (TREC_POW_OF_ATT_ID),
	constraint FK_TREC_POW_OF_ATT_TREC foreign key (TREC_ID) references TREC(TREC_ID),
	constraint FK_TREC_POW_OF_ATT_PERSON foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID)
);

------------------------------------------------------
 TREC_CAMALCO 
------------------------------------------------------

CREATE TABLE TREC_CAMALCO (
    TREC_CAMALCO_ID NUMBER(10) NOT NULL,
	TREC_ID NUMBER(5,0) NOT NULL,
	PERSONNEL_ID NUMBER(10,0) NOT NULL,
	EFFECTIVE_DATE DATE ,
	END_DATE  DATE ,
	
	REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    constraint PK_FK_TREC_CAMALCO primary key (TREC_CAMALCO_ID),
	constraint FK_TREC_CAMALCO_TREC foreign key (TREC_ID) references TREC(TREC_ID),
	constraint FK_TREC_CAMALCO_PERSON foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID)
);
 
--------------------------------------------------------------------------------
