
-----------------------------------------------------------------
 NET_CONNECTION_TYPE
-----------------------------------------------------------------

--drop table NET_CONNECTION_TYPE;
CREATE TABLE NET_CONNECTION_TYPE(
  NET_CONNECTION_TYPE_ID number(10) NOT NULL,
  CONNECTION_NAME VARCHAR2(255) NOT NULL,
  REMARKS VARCHAR2(255),
  IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
  constraint PK_NET_CONNECTION_TYPE_TYPE primary key (NET_CONNECTION_TYPE_ID)
);

-----------------------------------------------------------------
 NET_VENDOR
-----------------------------------------------------------------

--drop table NET_VENDOR;
CREATE TABLE NET_VENDOR(
  NET_VENDOR_ID number(10) NOT NULL,
  VENDOR_NAME VARCHAR2(255) NOT NULL,
  REMARKS VARCHAR2(255),
  IS_ACTIVE number(1) DEFAULT (1) NOT NULL,,
  constraint PK_NET_VENDOR_ID primary key (NET_VENDOR_ID)
);

-----------------------------------------------------------------
 BD_DIVISION
-----------------------------------------------------------------

--drop table BD_DIVISION;
CREATE TABLE BD_DIVISION(
  DIVISION_ID number(10) NOT NULL,
  DIVISION_NAME VARCHAR2(50) NOT NULL,
  URL VARCHAR2(100),
  REMARKS VARCHAR2(255),
  IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
  constraint PK_BD_DIVISION_ID primary key (DIVISION_ID)
);

-----------------------------------------------------------------
 BD_DISTRICT
-----------------------------------------------------------------

--drop table BD_DISTRICT;
CREATE TABLE BD_DISTRICT(
  DISTRICT_ID number(10) NOT NULL,
  DIVISION_ID number(10) NOT NULL,
  DISTRICT_NAME VARCHAR2(255) NOT NULL,
  URL VARCHAR2(100),
  REMARKS VARCHAR2(255),
  IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
  constraint PK_BD_DISTRICT_ID primary key (DISTRICT_ID),
  CONSTRAINT FK_BD_DISTRICT_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES BD_DIVISION(DIVISION_ID)
);
--------------------------------------------------------------------------------

DELETE from OFFICE;
commit;

SELECT constraint_name, table_name
FROM user_constraints
WHERE r_constraint_name IN (
  SELECT constraint_name
  FROM user_constraints
  WHERE table_name = 'OFFICE'
    AND constraint_type IN ('P', 'U')
);

-- Delete a office record
select * from OFFICE where TREC_ID = 181 and OFFICE_ID = 2344 ;
select * from OFFICE_TYPE where OFFICE_ID = 2344;

delete from OFFICE_TYPE where OFFICE_ID = 2344 ;
delete from OFFICE_STATUS where OFFICE_ID = 2344 ;
delete from OFFICE_ADDRESS where OFFICE_ID = 2344 ;
delete from OFFICE_INCHARGE where OFFICE_ID = 2344 ;
delete from OFFICE_COMPL_OFFICER where OFFICE_ID = 2344 ;
delete from OFFICE_NETWORK where OFFICE_ID = 2344 ;
delete from WORKSTATION_OFFICE where OFFICE_ID = 2344 ;
delete from OFFICE where OFFICE_ID = 2344 ;
commit;

-- Drop the foreign key constraints for each table and key

ALTER TABLE WORKSTATION_OFFICE DROP CONSTRAINT FK_WRKST_OFFICE_OFFICE;

-- ADD the foreign key constraints for each table and key

ALTER TABLE WORKSTATION_OFFICE ADD CONSTRAINT FK_WRKST_OFFICE_OFFICE FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(OFFICE_ID);

-----------------------------------------------------------------
 OFFICE
-----------------------------------------------------------------

CREATE TABLE OFFICE(
    OFFICE_ID NUMBER(5,0)NOT NULL,
    BACKUP_ID NUMBER(5,0),
	TREC_ID NUMBER(5,0) NOT NULL,         -- OFFICE_BACKUP.MEM_NO  
	-- OFFICE_TYPE VARCHAR2(40 CHAR),     -- OFFICE_BACKUP.BRNCHTYPE 
	OFFICE_NO NUMBER(5,0),    		      -- OFFICE_BACKUP.BRNCHNO 
	OFFICE_NAME VARCHAR2(255 CHAR), 
    BSEC_APPROVAL_DATE DATE,   			  -- OFFICE_BACKUP.ACTIONDATE
	DSE_APPROVAL_DATE DATE, 

    OFFICE_CONTACT_NO VARCHAR2(50 CHAR),   -- OFFICE_BACKUP.CONTACTNO
    OFFICE_EMAIL VARCHAR2(255 CHAR),

	REMARKS VARCHAR2(999),				    -- OFFICE_BACKUP.REMARK 
	--STATUS VARCHAR2(50) NOT NULL, 	    -- OFFICE_BACKUP.STATUS
    --STATUS_EFFECTIVE_DATE DATE,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

	constraint PK_OFFICE_ID primary key (OFFICE_ID),
    constraint FK_OFFICE_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);

-----------------------------------------------------------------
 OFFICE_TYPE
-----------------------------------------------------------------

CREATE TABLE OFFICE_TYPE(
    OFFICE_TYPE_ID NUMBER(10,0) NOT NULL,
	OFFICE_ID NUMBER(5,0) NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,             -- OFFICE_BACKUP.BRNCHTYPE 
    EFFECTIVE_DATE DATE,                    -- OFFICE_BACKUP.ACTIONDATE
    END_DATE DATE,
	REMARKS VARCHAR2(255),		

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_OFFICE_TYPE_ID PRIMARY KEY (OFFICE_TYPE_ID),
    CONSTRAINT FK_OFFICE_TYPE_OFFICE_ID FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(OFFICE_ID)
);

-----------------------------------------------------------------
 OFFICE_STATUS
-----------------------------------------------------------------

CREATE TABLE OFFICE_STATUS(
    OFFICE_STATUS_ID NUMBER(10,0) NOT NULL,
	OFFICE_ID NUMBER(5,0) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    EFFECTIVE_DATE DATE,                    -- OFFICE_BACKUP.ACTIONDATE
    END_DATE DATE,
	REMARKS VARCHAR2(255),		

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_OFFICE_STATUS_ID PRIMARY KEY (OFFICE_STATUS_ID),
    CONSTRAINT FK_OFFICE_STATUS_OFFICE_ID FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(OFFICE_ID)
);

------------------------------------------------------
 OFFICE_ADDRESS
------------------------------------------------------

CREATE TABLE OFFICE_ADDRESS(
    OFFICE_ADDRESS_ID NUMBER(10,0)  NOT NULL,
	OFFICE_ID NUMBER(5,0) NOT NULL,
    --BRLOC VARCHAR2(999 CHAR),  	   -- BRANCH LOCATION -- Duplicate
	LOCATION VARCHAR2(255 CHAR),       -- OFFICE_BACKUP.BRNCHLOC 
	AREA VARCHAR2(255 CHAR),           -- OFFICE_BACKUP.BRNCHAREA
	THANA VARCHAR2(255 CHAR), 
	EUNION VARCHAR2(255 CHAR),
	
    DISTRICT VARCHAR2(50),
    DIVISION VARCHAR2(255),

    OPERATION_START_DATE DATE,
	OPERATION_END_DATE DATE,

    IS_PANEL_BROKING number(1) DEFAULT (0) NOT NULL,
	PANEL_BROKER VARCHAR2(255 CHAR),

    SPACE_SIZE VARCHAR2(255 CHAR), 
    IS_RENTED number(1) DEFAULT (0) NOT NULL,
	RENTED_FROM_DATE DATE,   			   
	RENTED_TO_DATE DATE,   			   

	REMARKS VARCHAR2(255),				
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
	
	constraint PK_OFFICE_ADDRESS_ID primary key (OFFICE_ADDRESS_ID),
	constraint FK_OFFICE_ADDRESS_OFFICE foreign key (OFFICE_ID) references OFFICE(OFFICE_ID)
);


------------------------------------------------------
 OFFICE_NETWORK
------------------------------------------------------

CREATE TABLE OFFICE_NETWORK(
    OFFICE_NETWORK_ID NUMBER(10,0)  NOT NULL,
	OFFICE_ID NUMBER(5,0) NOT NULL,
    NET_VENDOR_ID NUMBER(10,0), 
    --VENDOR VARCHAR2(255 CHAR),  		 -- OFFICE_BACKUP.VENDOR 

    NET_CONNECTION_TYPE_ID NUMBER(10,0), 
    --CONTYPE VARCHAR2(50 CHAR), 		 -- OFFICE_BACKUP.CONTYPE 
    BRNCHIP VARCHAR2(30 CHAR),  		 -- OFFICE_BACKUP.BRNCHIP
    GATEWAY VARCHAR2(30 CHAR), 			 -- OFFICE_BACKUP.GATEWAY 
    MSA VARCHAR2(10 CHAR), 				 -- OFFICE_BACKUP.MSA 

    EFFECTIVE_DATE DATE,
	END_DATE DATE,

	REMARKS VARCHAR2(255),				
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
	
	constraint PK_OFFICE_NET_ID primary key (OFFICE_NETWORK_ID),
	constraint FK_OFFICE_NET_OFFICE foreign key (OFFICE_ID) references OFFICE(OFFICE_ID)
);

--------------------------------------------------------------------------------
 OFFICE_INCHARGE 
--------------------------------------------------------------------------------

CREATE TABLE OFFICE_INCHARGE(
    OFFICE_INCHARGE_ID NUMBER(10,0) NOT NULL,
	OFFICE_ID NUMBER(5,0) NOT NULL,
    PERSONNEL_ID NUMBER(10,0) NOT NULL,
	EFFECTIVE_DATE DATE,
	END_DATE DATE,
	
	REMARKS VARCHAR2(500),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

	ADDED_AT DATE DEFAULT sysdate NOT NULL,
	ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

	constraint PK_OF_INCHARGE_ID primary key (OFFICE_INCHARGE_ID),
	constraint FK_OF_INCHARGE_OFFICE foreign key (OFFICE_ID) references OFFICE(OFFICE_ID),
    constraint FK_OF_INCHARGE_PERSON foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID)
);

--------------------------------------------------------------------------------
 OFFICE_COMPL_OFFICER
--------------------------------------------------------------------------------

CREATE TABLE OFFICE_COMPL_OFFICER(
    OFFICE_COMPL_OFFICER_ID NUMBER(10,0) NOT NULL,
	OFFICE_ID NUMBER(5,0) NOT NULL,
    PERSONNEL_ID NUMBER(10,0) NOT NULL,
	EFFECTIVE_DATE DATE,
	END_DATE DATE,
	
	REMARKS VARCHAR2(500),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

	ADDED_AT DATE DEFAULT sysdate NOT NULL,
	ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

	constraint PK_OF_COMPL_OFFICER_ID primary key (OFFICE_COMPL_OFFICER_ID),
	constraint FK_OF_COMPL_OFFICER_OFFICE foreign key (OFFICE_ID) references OFFICE(OFFICE_ID),
    constraint FK_OF_COMPL_OFFICER_PERSON foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID)
);

------------------------------------------------------
 VW_OFFICE
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
"OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE", "REMARKS",
"OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE",
"OFFICE_ADDRESS_ID", "LOCATION", "AREA", "THANA", "EUNION", "DIVISION", "DISTRICT","OPERATION_START_DATE", "OPERATION_END_DATE", "IS_PANEL_BROKING", "PANEL_BROKER", "SPACE_SIZE", "IS_RENTED", "RENTED_FROM_DATE", "RENTED_TO_DATE",
"OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", "IS_ACTIVE",
"INCHARGE_PERSONNEL_ID", "INCHARGE_NAME", "INCHARGE_DESIGNATION", "INCHARGE_SEX", "INCHARGE_NID", "INCHARGE_OFFICIAL_CONTACT_NO", "INCHARGE_PERSONAL_CONTACT_NO", "INCHARGE_OFFICIAL_EMAIL", "INCHARGE_PERSONAL_EMAIL",
"CO_PERSONNEL_ID", "CO_NAME", "CO_DESIGNATION", "CO_SEX", "CO_NID", "CO_OFFICIAL_CONTACT_NO", "CO_PERSONAL_CONTACT_NO", "CO_OFFICIAL_EMAIL", "CO_PERSONAL_EMAIL" 
) AS 

SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,
    o.REMARKS,

    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE, 
    ot.END_DATE as TYPE_END_DATE, 
    
    oa.OFFICE_ADDRESS_ID,
    oa.LOCATION,
    oa.AREA,
    oa.THANA,
    oa.EUNION,
    oa.DIVISION,
    oa.DISTRICT,
    --div.DIVISION_ID,
    --div.DIVISION_NAME,
    --dis.DISTRICT_ID,
    --dis.DISTRICT_NAME,
    oa.OPERATION_START_DATE,
    oa.OPERATION_END_DATE,
    oa.IS_PANEL_BROKING,
    oa.PANEL_BROKER,
    oa.SPACE_SIZE,
    oa.IS_RENTED,
    oa.RENTED_FROM_DATE,
    oa.RENTED_TO_DATE,

    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    CASE WHEN st.STATUS IN ('ACTIVE', 'RESUMED') THEN 1 ELSE 0 END AS IS_ACTIVE,

    pioi.PERSONNEL_ID As INCHARGE_PERSONNEL_ID,
    pioi.NAME as INCHARGE_NAME,
    pioi.DESIGNATION as INCHARGE_DESIGNATION,
    pioi.SEX as INCHARGE_SEX,
    pioi.NID as INCHARGE_NID,
    pioi.OFFICIAL_CONTACT_NO as INCHARGE_OFFICIAL_CONTACT_NO,
    pioi.PERSONAL_CONTACT_NO as INCHARGE_PERSONAL_CONTACT_NO,
    pioi.OFFICIAL_EMAIL as INCHARGE_OFFICIAL_EMAIL,
    pioi.PERSONAL_EMAIL as INCHARGE_PERSONAL_EMAIL,
    
    pioco.PERSONNEL_ID As CO_PERSONNEL_ID,
    pioco.NAME as CO_NAME,
    pioco.DESIGNATION as CO_DESIGNATION,
    pioco.SEX as CO_SEX,
    pioco.NID as CO_NID,
    pioco.OFFICIAL_CONTACT_NO as CO_OFFICIAL_CONTACT_NO,
    pioco.PERSONAL_CONTACT_NO as CO_PERSONAL_CONTACT_NO,
    pioco.OFFICIAL_EMAIL as CO_OFFICIAL_EMAIL,
    pioco.PERSONAL_EMAIL as CO_PERSONAL_EMAIL

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID AND st.IS_ACTIVE = 1
LEFT JOIN OFFICE_ADDRESS oa ON o.OFFICE_ID = oa.OFFICE_ID AND oa.IS_ACTIVE = 1
LEFT JOIN OFFICE_INCHARGE oi ON o.OFFICE_ID = oi.OFFICE_ID AND oi.IS_ACTIVE = 1
LEFT JOIN PERSONNEL pioi ON pioi.PERSONNEL_ID = oi.PERSONNEL_ID
LEFT JOIN OFFICE_COMPL_OFFICER oco ON o.OFFICE_ID = oco.OFFICE_ID AND oco.IS_ACTIVE = 1
LEFT JOIN PERSONNEL pioco ON pioco.PERSONNEL_ID = oco.PERSONNEL_ID
ORDER BY o.OFFICE_ID;

select * from VW_OFFICE;

------------------------------------------------------
 VW_OFFICE_NETWORK
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE_NETWORK" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
"OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE",
"OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE",
"OFFICE_ADDRESS_ID", "LOCATION", "AREA", "THANA", "EUNION", "DIVISION", "DISTRICT", "OPERATION_START_DATE", "OPERATION_END_DATE", "IS_PANEL_BROKING", "PANEL_BROKER", "SPACE_SIZE", "IS_RENTED", "RENTED_FROM_DATE", "RENTED_TO_DATE",
"OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", 
"OFFICE_NETWORK_ID", "BRNCHIP", "GATEWAY", "MSA", "NETWORK_EFFECTIVE_DATE", "NETWORK_END_DATE", "REMARKS", "IS_ACTIVE",
"NET_VENDOR_ID", "VENDOR_NAME", "VENDOR_REMARKS",
"NET_CONNECTION_TYPE_ID", "CONNECTION_NAME", "CONNECTION_REMARKS"
) AS 

SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,
    
    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,
    
    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE, 
    ot.END_DATE as TYPE_END_DATE, 
    
    oa.OFFICE_ADDRESS_ID,
    oa.LOCATION,
    oa.AREA,
    oa.THANA,
    oa.EUNION,
    oa.DIVISION,
    oa.DISTRICT,
    --div.DIVISION_ID,
    --div.DIVISION_NAME,
    --dis.DISTRICT_ID,
    --dis.DISTRICT_NAME,
    oa.OPERATION_START_DATE,
    oa.OPERATION_END_DATE,
    oa.IS_PANEL_BROKING,
    oa.PANEL_BROKER,
    oa.SPACE_SIZE,
    oa.IS_RENTED,
    oa.RENTED_FROM_DATE,
    oa.RENTED_TO_DATE,
    
    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    
    net.OFFICE_NETWORK_ID,
    net.BRNCHIP,
    net.GATEWAY,
    net.MSA,
    net.EFFECTIVE_DATE as NETWORK_EFFECTIVE_DATE,
    net.END_DATE as NETWORK_END_DATE,
    net.REMARKS,
    net.IS_ACTIVE,

    nv.NET_VENDOR_ID,
    nv.VENDOR_NAME,
    nv.REMARKS as VENDOR_REMARKS,

    nc.NET_CONNECTION_TYPE_ID,
    nc.CONNECTION_NAME,
    nc.REMARKS as CONNECTION_REMARKS

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID AND st.IS_ACTIVE = 1
LEFT JOIN OFFICE_ADDRESS oa ON o.OFFICE_ID = oa.OFFICE_ID AND oa.IS_ACTIVE = 1
INNER JOIN OFFICE_NETWORK net on o.OFFICE_ID = net.OFFICE_ID 
INNER JOIN NET_VENDOR nv on net.NET_VENDOR_ID = nv.NET_VENDOR_ID 
INNER JOIN NET_CONNECTION_TYPE nc on net.NET_CONNECTION_TYPE_ID = nc.NET_CONNECTION_TYPE_ID 
ORDER BY o.OFFICE_ID;

select * from VW_OFFICE_NETWORK;

------------------------------------------------------
 VW_OFFICE_STATUS
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE_STATUS" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
"OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE",
"OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE",
"OFFICE_ADDRESS_ID", "LOCATION", "AREA", "THANA", "EUNION", "DIVISION", "DISTRICT", "OPERATION_START_DATE", "OPERATION_END_DATE", "IS_PANEL_BROKING", "PANEL_BROKER", "SPACE_SIZE", "IS_RENTED", "RENTED_FROM_DATE", "RENTED_TO_DATE",
"OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", "IS_ACTIVE", "REMARKS"
) AS 

SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,
    
    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE, 
    ot.END_DATE as TYPE_END_DATE, 
    
    oa.OFFICE_ADDRESS_ID,
    oa.LOCATION,
    oa.AREA,
    oa.THANA,
    oa.EUNION,
    oa.DIVISION,
    oa.DISTRICT,
    --div.DIVISION_ID,
    --div.DIVISION_NAME,
    --dis.DISTRICT_ID,
    --dis.DISTRICT_NAME,
    oa.OPERATION_START_DATE,
    oa.OPERATION_END_DATE,
    oa.IS_PANEL_BROKING,
    oa.PANEL_BROKER,
    oa.SPACE_SIZE,
    oa.IS_RENTED,
    oa.RENTED_FROM_DATE,
    oa.RENTED_TO_DATE,
    
    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    st.IS_ACTIVE,
    st.REMARKS

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID
LEFT JOIN OFFICE_ADDRESS oa ON o.OFFICE_ID = oa.OFFICE_ID AND oa.IS_ACTIVE = 1
ORDER BY o.OFFICE_ID;

select * from VW_OFFICE_STATUS;

------------------------------------------------------
 VW_OFFICE_TYPE
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE_TYPE" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
"OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE", 
"OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE", "IS_ACTIVE", "REMARKS",
"OFFICE_ADDRESS_ID", "LOCATION", "AREA", "THANA", "EUNION", "DIVISION", "DISTRICT", "OPERATION_START_DATE", "OPERATION_END_DATE", "IS_PANEL_BROKING", "PANEL_BROKER", "SPACE_SIZE", "IS_RENTED", "RENTED_FROM_DATE", "RENTED_TO_DATE",
"OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE"
) AS 

SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,
    
    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE, 
    ot.END_DATE as TYPE_END_DATE, 
    ot.IS_ACTIVE,
    ot.REMARKS,
    
    oa.OFFICE_ADDRESS_ID,
    oa.LOCATION,
    oa.AREA,
    oa.THANA,
    oa.EUNION,
    oa.DIVISION,
    oa.DISTRICT,
    -- div.DIVISION_ID,
    -- div.DIVISION_NAME,
    -- dis.DISTRICT_ID,
    -- dis.DISTRICT_NAME,
    oa.OPERATION_START_DATE,
    oa.OPERATION_END_DATE,
    oa.IS_PANEL_BROKING,
    oa.PANEL_BROKER,
    oa.SPACE_SIZE,
    oa.IS_RENTED,
    oa.RENTED_FROM_DATE,
    oa.RENTED_TO_DATE,
    
    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID AND st.IS_ACTIVE = 1
LEFT JOIN OFFICE_ADDRESS oa ON o.OFFICE_ID = oa.OFFICE_ID AND oa.IS_ACTIVE = 1
ORDER BY o.OFFICE_ID;

select * from VW_OFFICE_TYPE;

------------------------------------------------------
 VW_OFFICE_ADDRESS
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE_ADDRESS" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
"OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE", 
"OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE",
"OFFICE_ADDRESS_ID", "LOCATION", "AREA", "THANA", "EUNION", "DIVISION", "DISTRICT",
"OPERATION_START_DATE", "OPERATION_END_DATE", "IS_PANEL_BROKING", "PANEL_BROKER", "SPACE_SIZE", "IS_RENTED", "RENTED_FROM_DATE", "RENTED_TO_DATE", "IS_ACTIVE", "REMARKS",
"OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE"
) AS 

SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,
    
    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE, 
    ot.END_DATE as TYPE_END_DATE, 

    oa.OFFICE_ADDRESS_ID,
    oa.LOCATION,
    oa.AREA,
    oa.THANA,
    oa.EUNION,
    oa.DIVISION,
    oa.DISTRICT,
    --div.DIVISION_ID,
    --div.DIVISION_NAME,
    --dis.DISTRICT_ID,
    --dis.DISTRICT_NAME,
    oa.OPERATION_START_DATE,
    oa.OPERATION_END_DATE,
    oa.IS_PANEL_BROKING,
    oa.PANEL_BROKER,
    oa.SPACE_SIZE,
    oa.IS_RENTED,
    oa.RENTED_FROM_DATE,
    oa.RENTED_TO_DATE,
    oa.IS_ACTIVE,
    oa.REMARKS,
    
    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID AND st.IS_ACTIVE = 1
INNER JOIN OFFICE_ADDRESS oa ON o.OFFICE_ID = oa.OFFICE_ID 
ORDER BY o.OFFICE_ID;

select * from VW_OFFICE_ADDRESS;


------------------------------------------------------
 VW_OFFICE_INCHARGE
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE_INCHARGE"
(
    --"VIEW_KEY", 
    "TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME",
    "OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE",
    "OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE",
    "OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE",
    "OFFICE_INCHARGE_ID", "INCHARGE_EFFECTIVE_DATE", "INCHARGE_END_DATE", "REMARKS", "IS_ACTIVE",
    "PERSONNEL_ID", "NAME", "SEX", "DATE_OF_BIRTH", "NAME_OF_FATHER", "NAME_OF_MOTHER", "NAME_OF_SPOUSE", "MAX_EDU_QUALIFICATION", "PRESENT_ADDRESS", "PERMANENT_ADDRESS",
    "NID", "ETIN", "DESIGNATION", "DATE_OF_JOINING", "OFFICIAL_CONTACT_NO", "PERSONAL_CONTACT_NO", "OFFICIAL_EMAIL", "DATE_OF_EMPLOYMENT_END",
    "PERSONAL_EMAIL", "ALTERNATIVE_EMAIL", "FAX", "RESIDENCE_STATUS", "IMAGE_PATH", "SIGNATURE_PATH"
) AS

SELECT
    --oi.OFFICE_INCHARGE || '_' || oi.PERSONNEL AS VIEW_KEY
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,

    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE,
    ot.END_DATE as TYPE_END_DATE,

    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,

    oi.OFFICE_INCHARGE_ID,
    oi.EFFECTIVE_DATE as INCHARGE_EFFECTIVE_DATE,
    oi.END_DATE as INCHARGE_END_DATE,
    oi.REMARKS,
    oi.IS_ACTIVE,

    pi.PERSONNEL_ID,
    pi.NAME,
    pi.SEX,
    pi.DATE_OF_BIRTH,
    pi.NAME_OF_FATHER,
    pi.NAME_OF_MOTHER,
    pi.NAME_OF_SPOUSE,
    pi.MAX_EDU_QUALIFICATION,
    pi.PRESENT_ADDRESS,
    pi.PERMANENT_ADDRESS,
    pi.NID,
    pi.ETIN,
    pi.DESIGNATION,
    pi.DATE_OF_JOINING,
    pi.OFFICIAL_CONTACT_NO,
    pi.PERSONAL_CONTACT_NO,
    pi.OFFICIAL_EMAIL,
    pi.DATE_OF_EMPLOYMENT_END,
    pi.PERSONAL_EMAIL,
    pi.ALTERNATIVE_EMAIL,
    pi.FAX,
    pi.RESIDENCE_STATUS,
    pi.IMAGE_PATH,
    pi.SIGNATURE_PATH

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot ON o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID AND st.IS_ACTIVE = 1
INNER JOIN OFFICE_INCHARGE oi ON o.OFFICE_ID = oi.OFFICE_ID
INNER JOIN PERSONNEL pi ON pi.PERSONNEL_ID = oi.PERSONNEL_ID
ORDER BY o.OFFICE_ID;


select * from VW_OFFICE_INCHARGE;


------------------------------------------------------
 VW_OFFICE_COMPL_OFFICER
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_OFFICE_COMPL_OFFICER"
(
    "TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME",
    "OFFICE_ID", "OFFICE_NO", "OFFICE_NAME", "OFFICE_CONTACT_NO", "OFFICE_EMAIL", "BSEC_APPROVAL_DATE", "DSE_APPROVAL_DATE",
    "OFFICE_TYPE_ID", "TYPE", "TYPE_EFFECTIVE_DATE", "TYPE_END_DATE",
    "OFFICE_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE",
    "OFFICE_COMPL_OFFICER_ID", "CO_EFFECTIVE_DATE", "CO_END_DATE", "REMARKS", "IS_ACTIVE",
    "PERSONNEL_ID", "NAME", "SEX", "DATE_OF_BIRTH", "NAME_OF_FATHER", "NAME_OF_MOTHER", "NAME_OF_SPOUSE", "MAX_EDU_QUALIFICATION", "PRESENT_ADDRESS", "PERMANENT_ADDRESS",
    "NID", "ETIN", "DESIGNATION", "DATE_OF_JOINING", "OFFICIAL_CONTACT_NO", "PERSONAL_CONTACT_NO", "OFFICIAL_EMAIL", "DATE_OF_EMPLOYMENT_END",
    "PERSONAL_EMAIL", "ALTERNATIVE_EMAIL", "FAX", "RESIDENCE_STATUS", "IMAGE_PATH", "SIGNATURE_PATH"
) AS

SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,
    o.OFFICE_CONTACT_NO,
    o.OFFICE_EMAIL,
    o.BSEC_APPROVAL_DATE,
    o.DSE_APPROVAL_DATE,

    ot.OFFICE_TYPE_ID,
    ot.TYPE,
    ot.EFFECTIVE_DATE as TYPE_EFFECTIVE_DATE,
    ot.END_DATE as TYPE_END_DATE,

    st.OFFICE_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,

    oc.OFFICE_COMPL_OFFICER_ID,
    oc.EFFECTIVE_DATE as CO_EFFECTIVE_DATE,
    oc.END_DATE as CO_END_DATE,
    oc.REMARKS,
    oc.IS_ACTIVE,

    pi.PERSONNEL_ID,
    pi.NAME,
    pi.SEX,
    pi.DATE_OF_BIRTH,
    pi.NAME_OF_FATHER,
    pi.NAME_OF_MOTHER,
    pi.NAME_OF_SPOUSE,
    pi.MAX_EDU_QUALIFICATION,
    pi.PRESENT_ADDRESS,
    pi.PERMANENT_ADDRESS,
    pi.NID,
    pi.ETIN,
    pi.DESIGNATION,
    pi.DATE_OF_JOINING,
    pi.OFFICIAL_CONTACT_NO,
    pi.PERSONAL_CONTACT_NO,
    pi.OFFICIAL_EMAIL,
    pi.DATE_OF_EMPLOYMENT_END,
    pi.PERSONAL_EMAIL,
    pi.ALTERNATIVE_EMAIL,
    pi.FAX,
    pi.RESIDENCE_STATUS,
    pi.IMAGE_PATH,
    pi.SIGNATURE_PATH

FROM OFFICE o
INNER JOIN TREC t ON o.TREC_ID = t.TREC_ID
INNER JOIN OFFICE_TYPE ot ON o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
INNER JOIN OFFICE_STATUS st ON o.OFFICE_ID = st.OFFICE_ID AND st.IS_ACTIVE = 1
INNER JOIN OFFICE_COMPL_OFFICER oc ON o.OFFICE_ID = oc.OFFICE_ID
INNER JOIN PERSONNEL pi ON pi.PERSONNEL_ID = oc.PERSONNEL_ID
ORDER BY o.OFFICE_ID;


select * from VW_OFFICE_COMPL_OFFICER;