------------------------------------------------------

DELETE from WORKSTATION;
commit;

SELECT constraint_name, table_name
FROM user_constraints
WHERE r_constraint_name IN (
  SELECT constraint_name
  FROM user_constraints
  WHERE table_name = 'WORKSTATION'
    AND constraint_type IN ('P', 'U')
);

delete from WORKSTATION_STATUS;
delete from WORKSTATION_OFFICE;
delete from WORKSTATION_AUTH_REP;
delete from WORKSTATION;
commit;

------------------------------------------------------
 WORKSTATION
------------------------------------------------------

CREATE TABLE WORKSTATION(
    WORKSTATION_ID NUMBER(5) NOT NULL,
	BACKUP_ID VARCHAR2(50 CHAR),
	TREC_ID NUMBER(5,0) NOT NULL,
	TWS_NAME VARCHAR2(10),
	TWS_CATERGORY VARCHAR2(4),
	TDRNO NUMBER(10),
    UCODE VARCHAR2(10),
	ID_TYPE VARCHAR2(1),
	EXP_DATE DATE,

    REMARKS VARCHAR2(255 CHAR), 
    --STATUS VARCHAR2(50 CHAR) NOT NULL,--
	--STATUS_EFFECTIVE_DATE DATE, -- ACTIONDATE

	ADDED_AT DATE DEFAULT sysdate NOT NULL, --CRT_DATE DATE,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    constraint PK_WORKSTATION primary key (WORKSTATION_ID),
    constraint FK_WORKSTATION_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);

--------------------------------------------------------------------------------

-- Drop the foreign key constraints for each table and key
ALTER TABLE WORKSTATION_OFFICE DROP CONSTRAINT FK_WRKST_OFFICE_WRKST;

-- ADD the foreign key constraints for each table and key
ALTER TABLE WORKSTATION_OFFICE ADD CONSTRAINT FK_WRKST_OFFICE_WRKST FOREIGN KEY (WORKSTATION_ID) REFERENCES WORKSTATION(WORKSTATION_ID);

------------------------------------------------------
 WORKSTATION_STATUS
------------------------------------------------------

CREATE TABLE WORKSTATION_STATUS(
    WORKSTATION_STATUS_ID NUMBER(10,0) NOT NULL,
	WORKSTATION_ID NUMBER(5,0) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    
    EFFECTIVE_DATE DATE,                    -- WORKSTATION.ACTIONDATE
    END_DATE DATE,

	REMARKS VARCHAR2(255),		
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

    ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),

    CONSTRAINT PK_WORKSTATION_STATUS_ID PRIMARY KEY (WORKSTATION_STATUS_ID),
    CONSTRAINT FK_WORKSTATION_STATUS_WORKST FOREIGN KEY (WORKSTATION_ID) REFERENCES WORKSTATION(WORKSTATION_ID)
);

------------------------------------------------------
 WORKSTATION_OFFICE
------------------------------------------------------

CREATE TABLE WORKSTATION_OFFICE(
    WORKSTATION_OFFICE_ID number(10) NOT NULL,
    WORKSTATION_ID number(5) NOT NULL,
    OFFICE_ID number(5) NOT NULL,

	EFFECTIVE_DATE DATE,
	END_DATE DATE,

    REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

	ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
	
    constraint PK_WRKST_OFFICE primary key (WORKSTATION_OFFICE_ID),
    constraint FK_WRKST_OFFICE_WRKST foreign key (WORKSTATION_ID) references WORKSTATION(WORKSTATION_ID),
	constraint FK_WRKST_OFFICE_OFFICE foreign key (OFFICE_ID) references OFFICE(OFFICE_ID)
);

------------------------------------------------------
 WORKSTATION_AUTH_REP
------------------------------------------------------

CREATE TABLE WORKSTATION_AUTH_REP(
    WORKSTATION_AUTH_REP_ID number(10) NOT NULL,
    AUTH_REP_ID number(10) NOT NULL,
	PERSONNEL_ID NUMBER(10,0) NOT NULL,
    WORKSTATION_ID NUMBER(5,0) NOT NULL,

	EFFECTIVE_DATE DATE,
	END_DATE DATE,

    REMARKS VARCHAR2(255 CHAR),
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,

	ADDED_AT DATE DEFAULT sysdate NOT NULL,
    ADDED_BY VARCHAR2(50) NOT NULL,

    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50),
	
    constraint PK_WORKSTATION_AUTH_REP primary key (WORKSTATION_AUTH_REP_ID),
    constraint FK_WORKSTATION_AUTH_REP_WS foreign key (WORKSTATION_ID) references WORKSTATION(WORKSTATION_ID),
    constraint FK_WORKSTATION_AUTH_REP_PRSN foreign key (PERSONNEL_ID) references PERSONNEL(PERSONNEL_ID),
    constraint FK_WORKSTATION_AUTH_REP_AR foreign key (AUTH_REP_ID) references AUTH_REP(AUTH_REP_ID)
);

------------------------------------------------------
 VW_WORKSTATION
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_WORKSTATION" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
 "WORKSTATION_ID", "TWS_NAME", "TWS_CATERGORY", "TDRNO", "UCODE", "ID_TYPE", "EXP_DATE", "REMARKS", "ADDED_AT", "ADDED_BY",
 "WORKSTATION_STATUS_ID", "STATUS","STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", "IS_ACTIVE",
 "OFFICE_ID", "OFFICE_NO",  "OFFICE_NAME", 
 "OFFICE_TYPE_ID", "TYPE",
 "LOCATION", "AREA", "THANA", "EUNION", "DISTRICT", "DIVISION", "IS_PANEL_BROKING", "PANEL_BROKER", "SPACE_SIZE", "IS_RENTED", "RENTED_FROM_DATE", "RENTED_TO_DATE",
 "PERSONNEL_ID","PERSONNEL_NAME","DESIGNATION","SEX","NID","OFFICIAL_CONTACT_NO", "PERSONAL_CONTACT_NO", "OFFICIAL_EMAIL", "PERSONAL_EMAIL",
  "AUTH_REP_ID", "BSEC_REG_NO"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    w.WORKSTATION_ID,
    w.TWS_NAME,
    w.TWS_CATERGORY,
    w.TDRNO,
    w.UCODE,
    w.ID_TYPE,
    w.EXP_DATE,
    w.REMARKS,
    w.ADDED_AT,
    w.ADDED_BY,

    st.WORKSTATION_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    CASE WHEN st.STATUS IN ('ACTIVE') THEN 1 ELSE 0 END AS IS_ACTIVE,
    
    o.OFFICE_ID,
    o.OFFICE_NO,
    o.OFFICE_NAME,

    o.OFFICE_TYPE_ID,
    o.TYPE,
  
    o.LOCATION,
    o.AREA,
    o.THANA,
    o.EUNION,
    o.DISTRICT,
    o.DIVISION,
    o.IS_PANEL_BROKING,
    o.PANEL_BROKER,
    o.SPACE_SIZE,
    o.IS_RENTED,
    o.RENTED_FROM_DATE,
    o.RENTED_TO_DATE,

    pi.PERSONNEL_ID,
    pi.NAME as PERSONNEL_NAME,
    pi.DESIGNATION,
    pi.SEX,
    pi.NID,
    pi.OFFICIAL_CONTACT_NO,
    pi.PERSONAL_CONTACT_NO,
    pi.OFFICIAL_EMAIL,
    pi.PERSONAL_EMAIL,

    ar.AUTH_REP_ID,
    ar.BSEC_REG_NO
    
FROM  WORKSTATION w
INNER JOIN TREC t ON w.TREC_ID = t.TREC_ID
INNER JOIN WORKSTATION_STATUS st ON st.WORKSTATION_ID = w.WORKSTATION_ID AND st.IS_ACTIVE = 1
LEFT JOIN WORKSTATION_OFFICE wo ON w.WORKSTATION_ID = wo.WORKSTATION_ID AND wo.IS_ACTIVE = 1
LEFT JOIN VW_OFFICE o ON wo.OFFICE_ID = o.OFFICE_ID
LEFT JOIN WORKSTATION_AUTH_REP war ON w.WORKSTATION_ID = war.WORKSTATION_ID AND war.IS_ACTIVE = 1
LEFT JOIN PERSONNEL pi ON pi.PERSONNEL_ID = war.PERSONNEL_ID
LEFT JOIN AUTH_REP ar ON pi.PERSONNEL_ID = ar.PERSONNEL_ID
ORDER BY w.WORKSTATION_ID;

select * from VW_WORKSTATION;

------------------------------------------------------
 VW_WORKSTATION_STATUS
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_WORKSTATION_STATUS" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
 "WORKSTATION_ID", "TWS_NAME", "TWS_CATERGORY", "TDRNO", "UCODE", "ID_TYPE", "EXP_DATE",
 "WORKSTATION_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE", "STATUS_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY"
 ) AS 
 
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE as TREC_CODE,
    t.NAME as TREC_NAME,

    w.WORKSTATION_ID,
    w.TWS_NAME,
    w.TWS_CATERGORY,
    w.TDRNO,
    w.UCODE,
    w.ID_TYPE,
    w.EXP_DATE,
    
    st.WORKSTATION_STATUS_ID,
    st.STATUS,
    st.EFFECTIVE_DATE as STATUS_EFFECTIVE_DATE,
    st.END_DATE as STATUS_END_DATE,
    st.REMARKS,
    st.IS_ACTIVE,
    st.ADDED_AT,
    st.ADDED_BY
    
FROM  WORKSTATION w
INNER JOIN TREC t on t.TREC_ID = w.TREC_ID
INNER JOIN WORKSTATION_STATUS st ON st.WORKSTATION_ID = w.WORKSTATION_ID
ORDER BY w.WORKSTATION_ID;

select * from VW_WORKSTATION;

------------------------------------------------------
 VW_WORKSTATION_OFFICE
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_WORKSTATION_OFFICE" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
 "WORKSTATION_ID", "TWS_NAME", "TWS_CATERGORY", "TDRNO", "UCODE", "ID_TYPE", "EXP_DATE",
 "WORKSTATION_OFFICE_ID", "OFFICE_ID", "OFFICE_EFFECTIVE_DATE", "OFFICE_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY",
 "TYPE", "OFFICE_NO", "OFFICE_NAME", "LOCATION", "AREA", "THANA", "EUNION", "DISTRICT", "DIVISION"
 ) AS 

SELECT
    vo.TREC_ID,
    vo.TREC_NO,
    vo.TREC_CODE,
    vo.TREC_NAME,

    w.WORKSTATION_ID,
    w.TWS_NAME,
    w.TWS_CATERGORY,
    w.TDRNO,
    w.UCODE,
    w.ID_TYPE,
    w.EXP_DATE,
    
    wo.WORKSTATION_OFFICE_ID,
    wo.OFFICE_ID,
    wo.EFFECTIVE_DATE as OFFICE_EFFECTIVE_DATE,
    wo.END_DATE as OFFICE_END_DATE,
    wo.REMARKS,
    wo.IS_ACTIVE,
    wo.ADDED_AT,
    wo.ADDED_BY,

    vo.TYPE,
    vo.OFFICE_NO,
    vo.OFFICE_NAME,
    vo.LOCATION,
    vo.AREA,
    vo.THANA,
    vo.EUNION,
    vo.DISTRICT,
    vo.DIVISION
    
FROM  WORKSTATION w
INNER JOIN WORKSTATION_OFFICE wo ON wo.WORKSTATION_ID = w.WORKSTATION_ID
INNER JOIN VW_OFFICE vo ON vo.OFFICE_ID = wo.OFFICE_ID
ORDER BY w.WORKSTATION_ID;

select * from VW_WORKSTATION_OFFICE;

------------------------------------------------------
 VW_WORKSTATION_AUTH_REP
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_WORKSTATION_AUTH_REP" 
("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", 
 "WORKSTATION_ID", "TWS_NAME", "TWS_CATERGORY", "TDRNO", "UCODE", "ID_TYPE", "EXP_DATE",
 "WORKSTATION_AUTH_REP_ID", "AUTH_REP_ID",  "PERSONNEL_ID", "AR_EFFECTIVE_DATE", "AR_END_DATE", "REMARKS", "IS_ACTIVE", "ADDED_AT", "ADDED_BY",
 "DSE_APPROVED_DATE", "BSEC_REG_NO", "BSEC_REG_ISSUANCE_DATE", "LICESE_TYPE", "LICESE_PATH",
 "AUTH_REP_STATUS_ID", "STATUS", "STATUS_EFFECTIVE_DATE",  "STATUS_END_DATE",
 "AUTH_REP_RENEW_ID", "RENEW_DATE", "EXPIRY_DATE",
 "PERSONNEL_NAME","DESIGNATION","SEX","NID","OFFICIAL_CONTACT_NO", "PERSONAL_CONTACT_NO", "OFFICIAL_EMAIL", "PERSONAL_EMAIL"
 ) AS 

SELECT
    va.TREC_ID,
    va.TREC_NO,
    va.TREC_CODE,
    va.TREC_NAME,

    w.WORKSTATION_ID,
    w.TWS_NAME,
    w.TWS_CATERGORY,
    w.TDRNO,
    w.UCODE,
    w.ID_TYPE,
    w.EXP_DATE,
    
    war.WORKSTATION_AUTH_REP_ID,
    war.AUTH_REP_ID,
    war.PERSONNEL_ID,
    war.EFFECTIVE_DATE as AR_EFFECTIVE_DATE,
    war.END_DATE as AR_END_DATE,
    war.REMARKS,
    war.IS_ACTIVE,
    war.ADDED_AT,
    war.ADDED_BY,

    va.DSE_APPROVED_DATE,
    va.BSEC_REG_NO,
    va.BSEC_REG_ISSUANCE_DATE,
    va.LICESE_TYPE,
    va.LICESE_PATH,

    va.AUTH_REP_STATUS_ID,
    va.STATUS,
    va.STATUS_EFFECTIVE_DATE ,
    va.STATUS_END_DATE,
    
    va.AUTH_REP_RENEW_ID,
    va.RENEW_DATE,
    va.EXPIRY_DATE,

    va.PERSONNEL_NAME,
    va.DESIGNATION,
    va.SEX,
    va.NID,
    va.OFFICIAL_CONTACT_NO,
    va.PERSONAL_CONTACT_NO,
    va.OFFICIAL_EMAIL,
    va.PERSONAL_EMAIL

FROM  WORKSTATION w
INNER JOIN TREC t on t.TREC_ID = w.TREC_ID
INNER JOIN WORKSTATION_AUTH_REP war ON war.WORKSTATION_ID = w.WORKSTATION_ID
INNER JOIN VW_AUTH_REP va ON va.PERSONNEL_ID = war.PERSONNEL_ID
--INNER JOIN VW_AUTH_REP va ON va.AUTH_REP_ID = war.AUTH_REP_ID
ORDER BY w.WORKSTATION_ID;

select * from VW_WORKSTATION_AUTH_REP;

------------------------------------------------------
 VW_TREC_SUMMARY_COUNT
------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "TREC_TREC"."VW_TREC_SUMMARY_COUNT" ("TREC_ID", "TREC_NO", "TREC_CODE", "TREC_NAME", "STATUS", "IS_BROKER", "IS_DEALER", "OFFICE_COUNT", "EXTENSION_COUNT", "BRANCH_COUNT", "DIGITAL_BOOTH_COUNT", "WORKSTATION_COUNT", "AR_COUNT", "BROKER_DEALER_STATUS") AS 
select r.TREC_ID, r.TREC_NO, r.CODE,  r.NAME,  r.STATUS, r.IS_BROKER, r.IS_DEALER,  r.OFFICE_COUNT, r.EXTENSION_COUNT, r.BRANCH_COUNT, r.DIGITAL_BOOTH_COUNT, r.WORKSTATION_COUNT, r.AR_COUNT,
       CASE
        WHEN (r.IS_BROKER = 1 AND r.IS_DEALER = 1) THEN 'BROKER_DEALER'
        WHEN (r.IS_BROKER = 1 AND r.IS_DEALER = 0) THEN 'BROKER'
        WHEN (r.IS_BROKER = 0 AND r.IS_DEALER = 1) THEN 'DEALER'
        ELSE 'NONE'
      END AS BROKER_DEALER_STATUS
from (
SELECT
    t.TREC_ID,
    t.TREC_NO,
    t.CODE,
    t.NAME,
    t.STATUS,
    (
        SELECT COUNT(*) 
        FROM BROKER b
        INNER JOIN BROKER_STATUS bs on b.BROKER_ID = bs.BROKER_ID  AND bs.STATUS IN ('ACTIVE', 'SUSPENDED') AND bs.IS_ACTIVE = 1 -- 'ACTIVE', 'SUSPENDED', 'CANCELLED'
        WHERE b.TREC_ID = t.TREC_ID
    ) as IS_BROKER,
    (
        SELECT COUNT(*) 
        FROM DEALER d
        INNER JOIN DEALER_STATUS ds on d.DEALER_ID = ds.DEALER_ID  AND ds.STATUS IN ('ACTIVE', 'SUSPENDED') AND ds.IS_ACTIVE = 1 -- 'ACTIVE', 'SUSPENDED', 'CANCELLED'
        WHERE d.TREC_ID = t.TREC_ID
    ) as IS_DEALER,
    (
        SELECT COUNT(*) 
        FROM OFFICE o
        INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.IS_ACTIVE = 1
        INNER JOIN OFFICE_STATUS os on o.OFFICE_ID = os.OFFICE_ID AND os.STATUS IN ('ACTIVE', 'RESUMED') AND os.IS_ACTIVE = 1  --'ACTIVE', 'RESUMED', 'SUSPENDED', 'WITHDRAWN'
        WHERE o.TREC_ID = t.TREC_ID
    ) AS OFFICE_COUNT,
    (
        SELECT COUNT(*) 
        FROM OFFICE o
        INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.TYPE = 'EXTENSION' AND ot.IS_ACTIVE = 1
        INNER JOIN OFFICE_STATUS os on o.OFFICE_ID = os.OFFICE_ID  AND os.STATUS IN ('ACTIVE', 'RESUMED') AND os.IS_ACTIVE = 1 --'ACTIVE', 'RESUMED', 'SUSPENDED', 'WITHDRAWN'
        WHERE o.TREC_ID = t.TREC_ID
    ) AS EXTENSION_COUNT,
    (
        SELECT COUNT(*) 
        FROM OFFICE o
        INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID  AND ot.TYPE = 'BRANCH' AND ot.IS_ACTIVE = 1
        INNER JOIN OFFICE_STATUS os on o.OFFICE_ID = os.OFFICE_ID  AND os.STATUS IN ('ACTIVE', 'RESUMED') AND  os.IS_ACTIVE = 1 --'ACTIVE', 'RESUMED', 'SUSPENDED', 'WITHDRAWN'
        WHERE o.TREC_ID = t.TREC_ID
    ) AS BRANCH_COUNT,
    (
        SELECT COUNT(*) 
        FROM OFFICE o
        INNER JOIN OFFICE_TYPE ot on o.OFFICE_ID = ot.OFFICE_ID AND ot.TYPE = 'DIGITAL BOOTH' AND ot.IS_ACTIVE = 1
        INNER JOIN OFFICE_STATUS os on o.OFFICE_ID = os.OFFICE_ID  AND os.STATUS IN ('ACTIVE', 'RESUMED') AND os.IS_ACTIVE = 1 --'ACTIVE', 'RESUMED', 'SUSPENDED', 'WITHDRAWN'
        WHERE o.TREC_ID = t.TREC_ID
    ) AS DIGITAL_BOOTH_COUNT,
    (
        SELECT COUNT(*) 
        FROM WORKSTATION w
        INNER JOIN WORKSTATION_STATUS ws on w.WORKSTATION_ID = ws.WORKSTATION_ID AND ws.STATUS IN ('ACTIVE') AND ws.IS_ACTIVE = 1 --'ACTIVE', 'SELF_SUSPENDED', 'SUSPENDED_BY_DSE', 'DEACTIVATED_BY_DSE'
        WHERE w.TREC_ID = t.TREC_ID
    ) AS WORKSTATION_COUNT,
    (
        SELECT COUNT(*) 
        FROM AUTH_REP ar
        inner join AUTH_REP_STATUS st on st.AUTH_REP_ID = ar.AUTH_REP_ID and st.STATUS IN ('ACTIVE', 'RESUMED') AND st.IS_ACTIVE = 1 --'ACTIVE','SUSPENDED','RESUMED', 'INACTIVE','WITHDRAWN'
        WHERE ar.TREC_ID = t.TREC_ID
    ) AS AR_COUNT
FROM
    TREC t
ORDER BY t.TREC_ID
) r;

select * from VW_TREC_SUMMARY_COUNT;

------------------------------------------------------
BUG FIX
------------------------------------------------------

select * from AUTH_REP  ar where ar.BSEC_REG_NO='BSEC/AR/DSE/2018/6959' ; -- PERSONNEL_ID = 6555

select * from AUTH_REP  ar where ar.PERSONNEL_ID = 6555; -- AUTH_REP_ID = 4370;
select * from AUTH_REP  ar where ar.PERSONNEL_ID = 6545; -- AUTH_REP_ID = 4360;

select * from WORKSTATION_AUTH_REP where AUTH_REP_ID=4370;
--update WORKSTATION_AUTH_REP set AUTH_REP_ID=4360 where WORKSTATION_AUTH_REP_ID=303;
commit;
select * from WORKSTATION_AUTH_REP where AUTH_REP_ID=4360;

select * from WORKSTATION_AUTH_REP where PERSONNEL_ID=6555; 
--update WORKSTATION_AUTH_REP set AUTH_REP_ID=4370 where WORKSTATION_AUTH_REP_ID=252;
commit;
select * from WORKSTATION_AUTH_REP where AUTH_REP_ID=4370;

select * from WORKSTATION  where WORKSTATION_ID=2090; 
select * from WORKSTATION  where WORKSTATION_ID=2084; 
select * from WORKSTATION  where WORKSTATION_ID=2084; 


select * from AUTH_REP  ar
inner join WORKSTATION_AUTH_REP war on war.WORKSTATION_AUTH_REP_ID=ar.AUTH_REP_ID
where ar.AUTH_REP_ID=4370 ; -- PERSONNEL_ID = 6555

select * from WORKSTATION_AUTH_REP where WORKSTATION_ID=2090; 
select * from WORKSTATION_AUTH_REP where WORKSTATION_ID=2084; 

select * from WORKSTATION_AUTH_REP war
inner join AUTH_REP ar on war.PERSONNEL_ID = ar.PERSONNEL_ID 
and war.AUTH_REP_ID <> ar.AUTH_REP_ID;


UPDATE WORKSTATION_AUTH_REP war
SET war.AUTH_REP_ID = (
    SELECT ar.AUTH_REP_ID
    FROM AUTH_REP ar
    WHERE war.PERSONNEL_ID = ar.PERSONNEL_ID
    AND war.AUTH_REP_ID <> ar.AUTH_REP_ID
    AND ROWNUM = 1  -- Ensure only one row is returned
)
WHERE EXISTS (
    SELECT 1
    FROM AUTH_REP ar
    WHERE war.PERSONNEL_ID = ar.PERSONNEL_ID
    AND war.AUTH_REP_ID <> ar.AUTH_REP_ID
);
