SET DEFINE OFF

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (1.0, 1.0, 'Cumilla', 'www.comilla.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (2.0, 1.0, 'Feni', 'www.feni.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (3.0, 1.0, 'Brahmanbaria', 'www.brahmanbaria.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (4.0, 1.0, 'Rangamati', 'www.rangamati.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (5.0, 1.0, 'Noakhali', 'www.noakhali.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (6.0, 1.0, 'Chandpur', 'www.chandpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (7.0, 1.0, 'Lakshmipur', 'www.lakshmipur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (8.0, 1.0, 'Chattogram', 'www.chittagong.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (9.0, 1.0, 'Coxsbazar', 'www.coxsbazar.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (10.0, 1.0, 'Khagrachhari', 'www.khagrachhari.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (11.0, 1.0, 'Bandarban', 'www.bandarban.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (12.0, 2.0, 'Sirajganj', 'www.sirajganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (13.0, 2.0, 'Pabna', 'www.pabna.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (14.0, 2.0, 'Bogura', 'www.bogra.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (15.0, 2.0, 'Rajshahi', 'www.rajshahi.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (16.0, 2.0, 'Natore', 'www.natore.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (17.0, 2.0, 'Joypurhat', 'www.joypurhat.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (18.0, 2.0, 'Chapainawabganj', 'www.chapainawabganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (19.0, 2.0, 'Naogaon', 'www.naogaon.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (20.0, 3.0, 'Jashore', 'www.jessore.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (21.0, 3.0, 'Satkhira', 'www.satkhira.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (22.0, 3.0, 'Meherpur', 'www.meherpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (23.0, 3.0, 'Narail', 'www.narail.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (24.0, 3.0, 'Chuadanga', 'www.chuadanga.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (25.0, 3.0, 'Kushtia', 'www.kushtia.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (26.0, 3.0, 'Magura', 'www.magura.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (27.0, 3.0, 'Khulna', 'www.khulna.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (28.0, 3.0, 'Bagerhat', 'www.bagerhat.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (29.0, 3.0, 'Jhenaidah', 'www.jhenaidah.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (30.0, 4.0, 'Jhalakathi', 'www.jhalakathi.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (31.0, 4.0, 'Patuakhali', 'www.patuakhali.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (32.0, 4.0, 'Pirojpur', 'www.pirojpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (33.0, 4.0, 'Barisal', 'www.barisal.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (34.0, 4.0, 'Bhola', 'www.bhola.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (35.0, 4.0, 'Barguna', 'www.barguna.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (36.0, 5.0, 'Sylhet', 'www.sylhet.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (37.0, 5.0, 'Moulvibazar', 'www.moulvibazar.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (38.0, 5.0, 'Habiganj', 'www.habiganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (39.0, 5.0, 'Sunamganj', 'www.sunamganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (40.0, 6.0, 'Narsingdi', 'www.narsingdi.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (41.0, 6.0, 'Gazipur', 'www.gazipur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (42.0, 6.0, 'Shariatpur', 'www.shariatpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (43.0, 6.0, 'Narayanganj', 'www.narayanganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (44.0, 6.0, 'Tangail', 'www.tangail.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (45.0, 6.0, 'Kishoreganj', 'www.kishoreganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (46.0, 6.0, 'Manikganj', 'www.manikganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (47.0, 6.0, 'Dhaka', 'www.dhaka.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (48.0, 6.0, 'Munshiganj', 'www.munshiganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (49.0, 6.0, 'Rajbari', 'www.rajbari.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (50.0, 6.0, 'Madaripur', 'www.madaripur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (51.0, 6.0, 'Gopalganj', 'www.gopalganj.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (52.0, 6.0, 'Faridpur', 'www.faridpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (53.0, 7.0, 'Panchagarh', 'www.panchagarh.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (54.0, 7.0, 'Dinajpur', 'www.dinajpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (55.0, 7.0, 'Lalmonirhat', 'www.lalmonirhat.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (56.0, 7.0, 'Nilphamari', 'www.nilphamari.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (57.0, 7.0, 'Gaibandha', 'www.gaibandha.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (58.0, 7.0, 'Thakurgaon', 'www.thakurgaon.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (59.0, 7.0, 'Rangpur', 'www.rangpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (60.0, 7.0, 'Kurigram', 'www.kurigram.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (61.0, 8.0, 'Sherpur', 'www.sherpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (62.0, 8.0, 'Mymensingh', 'www.mymensingh.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (63.0, 8.0, 'Jamalpur', 'www.jamalpur.gov.bd');

INSERT INTO BD_DISTRICT (DISTRICT_ID, DIVISION_ID, DISTRICT_NAME, URL) 
VALUES (64.0, 8.0, 'Netrokona', 'www.netrokona.gov.bd');

-- Import Data into table BD_DISTRICT from file D:\RND\wcf-notification\TREC\InHouse\3 districts.xlsx . Task successful and sent to worksheet.
