
select * from WORKSTATION_ALLOCATION_APP;
select * from WORKSTATION_RELOCATION_APP;
select * from WORKSTATION_RESUMPTION_APP;
select * from WORKSTATION_SUSPENSION_APP;

delete from WORKSTATION_ALLOCATION_APP;
delete from WORKSTATION_RELOCATION_APP;
delete from WORKSTATION_RESUMPTION_APP;
delete from WORKSTATION_SUSPENSION_APP;

-- drop table WORKSTATION_ALLOCATION_APP;
-- drop table WORKSTATION_RELOCATION_APP;
-- drop table WORKSTATION_RESUMPTION_APP;
-- drop table WORKSTATION_SUSPENSION_APP;


CREATE TABLE WORKSTATION_ALLOCATION_APP(
    WORKSTATION_ALLOCATION_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,

    constraint PK_WRKST_ALLOCATION_APP primary key (WORKSTATION_ALLOCATION_APP_ID),
    constraint FK_WRKST_ALLOCATION_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);


CREATE TABLE WORKSTATION_RELOCATION_APP(
    WORKSTATION_RELOCATION_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,
    
    constraint PK_WRKST_RELOCATION_APP primary key (WORKSTATION_RELOCATION_APP_ID),
    constraint FK_WRKST_RELOCATION_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);

CREATE TABLE WORKSTATION_RESUMPTION_APP(
    WORKSTATION_RESUMPTION_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,

    constraint PK_WRKST_RESUME_APP primary key (WORKSTATION_RESUMPTION_APP_ID),
	constraint FK_WRKST_RESUMPTION_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);


CREATE TABLE WORKSTATION_SUSPENSION_APP(
    WORKSTATION_SUSPENSION_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,

    constraint PK_WRKST_SUSPENSION_APP primary key (WORKSTATION_SUSPENSION_APP_ID),
	constraint FK_WRKST_SUSPENSION_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);

