select * from AUTH_REP_APPOINTMENT_APP;
select * from AUTH_REP_REPLACEMENT_APP;
select * from AUTH_REP_WITHDRAWAL_APP;

delete from AUTH_REP_APPOINTMENT_APP;
delete from AUTH_REP_REPLACEMENT_APP;
delete from AUTH_REP_WITHDRAWAL_APP;

-- drop table AUTH_REP_APPOINTMENT_APP;
-- drop table AUTH_REP_REPLACEMENT_APP;
-- drop table AUTH_REP_WITHDRAWAL_APP;


CREATE TABLE AUTH_REP_APPOINTMENT_APP(
    AUTH_REP_APPOINTMENT_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,

    constraint PK_AR_APPOINTMENT_APP primary key (AUTH_REP_APPOINTMENT_APP_ID),
    constraint FK_AR_APPOINTMENT_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);


CREATE TABLE AUTH_REP_REPLACEMENT_APP(
    AUTH_REP_REPLACEMENT_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),
	
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,
    
    constraint PK_AR_REPLACEMENT_APP primary key (AUTH_REP_REPLACEMENT_APP_ID),
    constraint FK_AR_REPLACEMENT_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);


CREATE TABLE AUTH_REP_WITHDRAWAL_APP(
    AUTH_REP_WITHDRAWAL_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),
	
    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,

    constraint PK_AR_WITHDRAWAL_APP primary key (AUTH_REP_WITHDRAWAL_APP_ID),
    constraint FK_AR_WITHDRAWAL_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);






