
select * from OFFICE_INCHARGE_APP;
select * from OFFICE_COMPL_OFFICER_APP;

delete from OFFICE_INCHARGE_APP;
delete from OFFICE_COMPL_OFFICER_APP;

-- drop table OFFICE_INCHARGE_APP;
-- drop table OFFICE_COMPL_OFFICER_APP;


CREATE TABLE OFFICE_INCHARGE_APP(
    
    OFFICE_INCHARGE_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,
    
    constraint PK_OFFICE_INCHARGE_APP primary key (OFFICE_INCHARGE_APP_ID),
    constraint FK_OFFICE_INCHARGE_APP_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);

CREATE TABLE OFFICE_COMPL_OFFICER_APP(
    
    OFFICE_COMPL_OFFICER_APP_ID number(10) NOT NULL,
	TREC_ID number(5,0) NOT NULL,
	REQUIRED_DOC_PATH VARCHAR2(255 CHAR),
	DESCRIPTION varchar2(255), -- purpose of allocation 
	REMARKS varchar2(255), -- purpose of rejaction or special remarks 
    STATUS VARCHAR2(50 CHAR) NOT NULL CHECK (STATUS IN ('CREATED','VERIFIED','APPROVED','REJECTED')),
    
    ADDED_AT DATE DEFAULT SYSDATE NOT NULL,
    ADDED_BY VARCHAR2(50 CHAR),
    UPDATED_AT DATE,
    UPDATED_BY VARCHAR2(50 CHAR),

    IS_ACTIVE number(1) DEFAULT (1) NOT NULL,
    IS_DELETED number(1) DEFAULT (0) NOT NULL,
    
    constraint PK_OFFICE_COMPL_OFFICER_APP primary key (OFFICE_COMPL_OFFICER_APP_ID),
    constraint FK_OFFICE_COMPL_OFFICER_TREC foreign key (TREC_ID) references TREC(TREC_ID)
);







